name: Build and Deploy Docker Image

on:
  push:
    branches:
      - '**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      id: docker_build
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/real-time-chat-project:${{ github.sha }} .
        echo "IMAGE=${{ secrets.DOCKER_USERNAME }}/real-time-chat-project:${{ github.sha }}" >> $GITHUB_ENV

    - name: Push Docker Image (Main Branch Only)
      if: github.ref_name == 'main'
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/real-time-chat-project:${{ github.sha }}

    - name: Create Pull Request (Other Branches)
      if: github.ref_name != 'main'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Build Docker image for branch ${{ github.ref_name }}"
        title: "Build Docker image for branch ${{ github.ref_name }}"
        body: "This pull request includes the Docker image build for branch ${{ github.ref_name }}."
        base: main
        branch: ${{ github.ref_name }}
